---
abstract: 'DEPRECATED MooseX::Types for Log::Any'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Runtime: '0'
  Moose: '0'
  Test::Fatal: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Types-LogAny
no_index:
  file:
    - perlcritic.rc
provides:
  MooseX::Types::LogAny:
    file: lib/MooseX/Types/LogAny.pm
    version: '0.001003'
requires:
  Log::Any: '0'
  Log::Any::Adapter: '0'
  MooseX::Types: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/xenoterracide/moosex-types-logany/issues
  homepage: https://metacpan.org/dist/MooseX-Types-LogAny
  repository: git://github.com/xenoterracide/moosex-types-logany.git
version: '0.001003'
